generator.jooq.db.url=jdbc:postgresql://localhost:5432/RadDevelopment                                 
generator.jooq.db.username=postgres                                                                       
generator.jooq.db.password=postgres                                                                       
generator.jooq.db.schema=public   
generator.jooq.db.driver=org.postgresql.Driver